include:
  - project: 'dti/agd/templates/ci-templates-javascript'
    ref: master
    file: 'react.yml'

variables:
  NODE_VERSION: "20"
  DOCKER_IMAGE_NAME: "wtpc-frontend"
  K8S_APP_NAME: "wtpc-frontend"

deploy:qa:
  variables:
    K8S_NAMESPACE: "dev-wtpc-sim"
    REACT_APP_API_URL: "https://wtpc-qa.weg.net"
