include:
  - project: 'devops/templates/javascript-ci-templates'
    ref: k8s
    file: 'express-node20.yml'

variables:
  NEEDS_DEV: "false"
  USE_OLD_SONAR: "false"
  SONAR_QUALITY_GATE: "false"
  DOCKER_HOST_PORT: "19510"
  DOCKER_CONTAINER_PORT: "3000"
  AUTOMATIC_DEPLOYMENT_ON_DEV: "false"
  AUTOMATIC_DEPLOYMENT_ON_QA: "true"
  DOCKER_IMAGE_NAME: wtpc-frontend
  DOCKER_CONTAINER_NAME: wtpc-frontend  
  PRE_PROD_TEST: "false"
  
deploy:qa:
  variables:
   APP_ENV: "qa"
   NAMESPACE: "dev-wtpc-sim"
   K8S_CPU_REQ: 100m
   K8S_CPU_LIM: 120m
   K8S_MEM_REQ: 200Mi
   K8S_MEM_LIM: 300Mi
  tags:
    - docker
