# include:
#   - project: 'dti/agd/templates/ci-templates-javascript'
#     ref: master
#     file: 'react.yml'

# variables:
#   NODE_VERSION: "18"
#   DOCKER_IMAGE_NAME: "wtpc-frontend"
#   K8S_APP_NAME: "wtpc-frontend"

# deploy:qa:
#   variables:
#     K8S_NAMESPACE: "dev-wtpc-sim"
#     REACT_APP_API_URL: "https://wtpc-qa.weg.net"


include:
  - project: 'devops/templates/javascript-ci-templates'
    ref: k8s
    file: 'express-node16.yml'

variables:
  NEEDS_DEV: "false"
  USE_OLD_SONAR: "false"
  SONAR_QUALITY_GATE: "false"
  DOCKER_HOST_PORT: "3000"
  DOCKER_CONTAINER_PORT: "3000"
  AUTOMATIC_DEPLOYMENT_ON_DEV: "false"
  AUTOMATIC_DEPLOYMENT_ON_QA: "true"
  DOCKER_IMAGE_NAME: ens3-frontend
  DOCKER_CONTAINER_NAME: ens3-frontend  
  PRE_PROD_TEST: "false"
  
deploy:qa:
  variables:
   APP_ENV: "qa"
   NAMESPACE: "dev-ensaios-sim"
   K8S_CPU_REQ: 100m
   K8S_CPU_LIM: 120m
   K8S_MEM_REQ: 200Mi
   K8S_MEM_LIM: 300Mi
  tags:
    - docker
